# Generated by Django 5.1.3 on 2024-11-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('criacao', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('precisa ser feito', 'Precisa ser Feito')], default='importante', max_length=25)),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('pendente', 'Pendente'), ('adiado', 'Adiado')], default='pendente', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='nome', max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
