# Generated by Django 5.1.3 on 2024-11-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('criacao', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('precisa ser feito', 'Precisa ser Feito')], default='importante', max_length=25)),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('pendente', 'Pendente'), ('adiado', 'Adiado')], default='pendente', max_length=25)),
            ],
            options={
                'db_table': 'tbl_tarefas',
            },
        ),
        migrations.DeleteModel(
            name='Tarefas',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='tbl_usuarios',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.usuario'),
        ),
    ]
