# Generated by Django 5.1.3 on 2024-11-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_delete_tarefas_alter_usuario_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='usuario',
        ),
        migrations.AlterModelTable(
            name='tarefa',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
